[project]
name = "monorepo-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ramon Cardoso de Oliveira" }
]
requires-python = ">=3.12"
dependencies = []
